plugins {
    id 'com.android.application'
}

android {
    namespace 'com.chk.apkinstaller'
    compileSdk 35

    defaultConfig {
        applicationId 'com.chk.apkinstaller'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '3.3'
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
