import {MAX_ORDER_USDC} from './trading-config.mjs';
import http from 'node:http';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { URL, URLSearchParams } from 'node:url';

const PORT=Number(process.env.PORT||3000);
const UPSTREAM_PORT=Number(process.env.V11_UPSTREAM_PORT||(PORT+10));
const MCP_LINK_TOKEN=String(process.env.MCP_LINK_TOKEN||'');
const EDGE_URL=String(process.env.SUPABASE_EDGE_URL||'');
const SUPABASE_MCP_TOKEN=String(process.env.SUPABASE_MCP_TOKEN||'');
const BYBIT_API_KEY=String(process.env.BYBIT_API_KEY||'').trim();
const SERVER_VERSION='11.0.0';
const BYBIT='https://api.bybit.eu';
const CANONICAL_REPO='Chasmet/Binance-bybyt-';
const here=path.dirname(fileURLToPath(import.meta.url));

if(!MCP_LINK_TOKEN) throw new Error('MCP_LINK_TOKEN missing');

const child=spawn(process.execPath,['server-v10.mjs'],{cwd:here,env:{...process.env,PORT:String(UPSTREAM_PORT),V10_UPSTREAM_PORT:String(UPSTREAM_PORT+10)},stdio:['ignore','inherit','inherit']});
child.on('exit',(code,signal)=>console.error(`v10 exited code=${code} signal=${signal}`));

function json(res,status,data,extra={}){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','content-length':Buffer.byteLength(body),...extra});res.end(body);}
async function bodyText(req,max=1_000_000){let body='';for await(const chunk of req){body+=chunk;if(body.length>max)throw new Error('request_too_large');}return body;}
function constantEqual(a,b){const A=Buffer.from(String(a||''));const B=Buffer.from(String(b||''));return A.length===B.length&&crypto.timingSafeEqual(A,B);}
function validMcpPath(p){return p.startsWith('/mcp/')&&constantEqual(p.slice(5),MCP_LINK_TOKEN);}
function sha256(v){return crypto.createHash('sha256').update(String(v)).digest('hex');}
function edgeUrl(slug){const u=new URL(EDGE_URL);u.pathname=u.pathname.replace(/\/chk-binance-workspace-latest\/?$/,`/${slug}`);return u.toString();}
async function edge(slug,payload){if(!EDGE_URL||!SUPABASE_MCP_TOKEN)throw new Error('Supabase server bridge not configured');const r=await fetch(edgeUrl(slug),{method:'POST',headers:{'content-type':'application/json','x-chk-token':SUPABASE_MCP_TOKEN,accept:'application/json','user-agent':'chk-crypto-workspace-v11'},body:JSON.stringify(payload)});const text=await r.text();let data;try{data=JSON.parse(text||'{}');}catch{data={raw:text};}if(!r.ok)throw new Error(`${slug} ${r.status}: ${data?.error||data?.message||text.slice(0,180)}`);return data;}
async function waitForUpstream(){for(let i=0;i<80;i++){try{const r=await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/health`);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('v10_startup_timeout');}
async function upstreamRpc(msg){const r=await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/mcp/${encodeURIComponent(MCP_LINK_TOKEN)}`,{method:'POST',headers:{'content-type':'application/json','mcp-protocol-version':'2025-06-18',accept:'application/json'},body:JSON.stringify(msg)});const text=await r.text();if(!r.ok)throw new Error(`canonical_upstream_${r.status}: ${text.slice(0,180)}`);return text?JSON.parse(text):null;}
async function callV10(name,args={}){const out=await upstreamRpc({jsonrpc:'2.0',id:'v11-inner',method:'tools/call',params:{name,arguments:args}});if(out?.result?.isError)throw new Error(out?.result?.content?.[0]?.text||'canonical tool failed');return out?.result?.structuredContent??null;}
async function bybitPublic(pathname,params={}){const qs=new URLSearchParams();for(const[k,v]of Object.entries(params))if(v!==undefined&&v!==null&&String(v)!=='')qs.set(k,String(v));const r=await fetch(`${BYBIT}${pathname}${qs.size?`?${qs}`:''}`,{headers:{accept:'application/json','user-agent':'chk-crypto-workspace-v11'}});const text=await r.text();let root;try{root=JSON.parse(text||'{}');}catch{root={};}if(!r.ok||Number(root.retCode||0)!==0)throw new Error(`Bybit ${root.retCode??r.status}: ${root.retMsg||text.slice(0,180)}`);return root;}
function cleanSymbol(v){const s=String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,30);if(!s.endsWith('USDC')||s==='USDCUSDC')throw new Error('Seules les paires CRYPTO/USDC Spot sont autorisées');return s;}
function fp(){if(!BYBIT_API_KEY)throw new Error('BYBIT_API_KEY Render absente');return sha256(BYBIT_API_KEY);}

const tools=[
 {name:'get_workspace_info',title:'État CHK Crypto Workspace',description:'Retourne le statut canonique CHK Crypto, le dépôt officiel et les résumés Binance + Bybit EU. Utiliser ce tool en premier.',inputSchema:{type:'object',properties:{},additionalProperties:false}},
 {name:'get_portfolio_summary',title:'Résumé portefeuille Binance + Bybit',description:'Portefeuille live via la route canonique Render. Les données mises en cache sont explicitement marquées.',inputSchema:{type:'object',properties:{},additionalProperties:false}},
 {name:'list_assets',title:'Lister les actifs Binance + Bybit',description:'Liste les actifs des deux plateformes avec provenance.',inputSchema:{type:'object',properties:{top_n:{type:'integer',minimum:1,maximum:50}},additionalProperties:false}},
 {name:'get_asset',title:'Détail d’un actif',description:'Recherche un actif sur Binance et Bybit.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false}},
 {name:'get_latest_snapshot',title:'Snapshot CHK Crypto',description:'État complet actuel du Workspace canonique.',inputSchema:{type:'object',properties:{},additionalProperties:false}},
 {name:'get_bybit_connection_info',title:'Connexion Bybit EU',description:'Vérifie les permissions Bybit EU et SpotTrade via les clés Render.',inputSchema:{type:'object',properties:{},additionalProperties:false}},
 {name:'get_bybit_portfolio_summary',title:'Portefeuille Bybit EU',description:'Résumé live du portefeuille Bybit EU.',inputSchema:{type:'object',properties:{},additionalProperties:false}},
 {name:'list_bybit_assets',title:'Actifs Bybit EU',description:'Liste les actifs Bybit EU.',inputSchema:{type:'object',properties:{top_n:{type:'integer',minimum:1,maximum:50}},additionalProperties:false}},
 {name:'list_bybit_open_orders',title:'Ordres Bybit ouverts',description:'Liste les ordres Spot Bybit EU réellement ouverts.',inputSchema:{type:'object',properties:{symbol:{type:'string'},limit:{type:'integer',minimum:1,maximum:50}},additionalProperties:false}},
 {name:'list_bybit_recent_executions',title:'Exécutions Bybit récentes',description:'Liste les exécutions Spot récentes sur Bybit EU.',inputSchema:{type:'object',properties:{symbol:{type:'string'},limit:{type:'integer',minimum:1,maximum:100}},additionalProperties:false}},
 {name:'list_bybit_usdc_markets',title:'Marchés Bybit USDC',description:'Liste les marchés Spot CRYPTO/USDC Bybit EU.',inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:100}},additionalProperties:false}},
 {name:'get_bybit_market_snapshot',title:'Analyse marché Bybit multi-timeframe',description:'Ticker, carnet et chandeliers 1m/1h/1j/1w pour une paire USDC.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false}},
 {name:'get_bybit_instrument_rules',title:'Règles ordre Bybit',description:'Retourne minOrderAmt, qtyStep, tickSize et précisions officielles de la paire.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false}},
 {name:'create_trade_proposal',title:'Créer une proposition d’ordre CHK Crypto',description:'Crée une proposition BUY/SELL Spot USDC dans CHK Crypto. Ne place AUCUN ordre réel. Le bot APK peut auto-confirmer si Auto-Trade et les autorisations sont activés.',inputSchema:{type:'object',properties:{symbol:{type:'string'},side:{type:'string',enum:['BUY','SELL']},order_type:{type:'string',enum:['LIMIT','MARKET']},quote_amount_usdc:{type:'number',exclusiveMinimum:1,maximum:MAX_ORDER_USDC},base_quantity:{type:'number',exclusiveMinimum:0},limit_price:{type:'number',exclusiveMinimum:0},rationale:{type:'string'},confidence:{type:'integer',minimum:0,maximum:99},expires_in_minutes:{type:'integer',minimum:5,maximum:1440}},required:['symbol','side','order_type','quote_amount_usdc','rationale'],additionalProperties:false}},
 {name:'list_trade_proposals',title:'Lister les propositions CHK Crypto',description:'Liste les propositions d’ordres CHK Crypto et leurs statuts.',inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:100}},additionalProperties:false}},
 {name:'create_cancel_proposal',title:'Proposer annulation/remplacement Bybit',description:'Crée une proposition d’annulation d’un ordre Bybit, éventuellement avec un ordre de remplacement. Le bot APK peut auto-confirmer si annuler/remplacer est autorisé.',inputSchema:{type:'object',properties:{symbol:{type:'string'},target_order_id:{type:'string'},target_order_link_id:{type:'string'},rationale:{type:'string'},confidence:{type:'integer',minimum:0,maximum:99},expires_in_minutes:{type:'integer',minimum:5,maximum:1440},replacement_side:{type:'string',enum:['BUY','SELL']},replacement_order_type:{type:'string',enum:['LIMIT','MARKET']},replacement_quote_amount_usdc:{type:'number',exclusiveMinimum:1,maximum:MAX_ORDER_USDC},replacement_base_quantity:{type:'number',exclusiveMinimum:0},replacement_limit_price:{type:'number',exclusiveMinimum:0},replacement_rationale:{type:'string'},replacement_confidence:{type:'integer',minimum:0,maximum:99}},required:['symbol','target_order_id','rationale'],additionalProperties:false}},
 {name:'list_cancel_proposals',title:'Lister les annulations proposées',description:'Liste les propositions d’annulation/remplacement.',inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:100}},additionalProperties:false}},
 {name:'create_note',title:'Écrire dans le bloc-notes CHK Crypto',description:'Ajoute une note d’analyse dans CHK Crypto pour la continuité des tâches.',inputSchema:{type:'object',properties:{content:{type:'string'},exchange:{type:'string'},kind:{type:'string'}},required:['content'],additionalProperties:false}},
 {name:'list_notes',title:'Lire le bloc-notes CHK Crypto',description:'Liste les notes actives CHK Crypto.',inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:200}},additionalProperties:false}},
];

const forwarded=new Set(['get_portfolio_summary','list_assets','get_asset','get_latest_snapshot','get_bybit_connection_info','get_bybit_portfolio_summary','list_bybit_assets','list_bybit_open_orders','list_bybit_recent_executions','list_bybit_usdc_markets']);
function rpcResult(id,data,text){return{jsonrpc:'2.0',id,result:{content:[{type:'text',text}],structuredContent:data}};}
async function executeTool(name,args={}){
 if(name==='get_workspace_info'){const summary=await callV10('get_portfolio_summary',{});let health=null;try{const r=await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/health`);health=await r.json();}catch{}return{workspace:'CHK Crypto Workspace',canonical:true,repository:CANONICAL_REPO,branch:'main',androidPackage:'com.chk.binancebybit',bybitEndpoint:BYBIT,executionPolicy:'proposal -> CONFIRMER dans APK -> Bybit EU Spot',directMcpTrading:false,legacyCredentialServiceUsed:false,summary,health};}
 if(forwarded.has(name))return await callV10(name,args);
 if(name==='get_bybit_market_snapshot'){const symbol=cleanSymbol(args.symbol);const [ticker,book,m1,h1,d1,w1]=await Promise.all([bybitPublic('/v5/market/tickers',{category:'spot',symbol}),bybitPublic('/v5/market/orderbook',{category:'spot',symbol,limit:50}),bybitPublic('/v5/market/kline',{category:'spot',symbol,interval:'1',limit:120}),bybitPublic('/v5/market/kline',{category:'spot',symbol,interval:'60',limit:120}),bybitPublic('/v5/market/kline',{category:'spot',symbol,interval:'D',limit:120}),bybitPublic('/v5/market/kline',{category:'spot',symbol,interval:'W',limit:120})]);const map=r=>(Array.isArray(r?.result?.list)?r.result.list:[]).map(k=>({time:Number(k[0]),open:Number(k[1]),high:Number(k[2]),low:Number(k[3]),close:Number(k[4]),volume:Number(k[5]),turnover:Number(k[6])})).reverse();return{symbol,ticker:ticker?.result?.list?.[0]||{},orderbook:book?.result||{},candles:{m1:map(m1),h1:map(h1),d1:map(d1),w1:map(w1)}};}
 if(name==='get_bybit_instrument_rules'){const symbol=cleanSymbol(args.symbol);const r=await bybitPublic('/v5/market/instruments-info',{category:'spot',symbol});const x=r?.result?.list?.[0];if(!x)throw new Error('Paire introuvable');return{symbol,status:x.status,lotSizeFilter:x.lotSizeFilter,priceFilter:x.priceFilter,basePrecision:x.basePrecision,quotePrecision:x.quotePrecision};}
 if(name==='create_trade_proposal'){const symbol=cleanSymbol(args.symbol);return await edge('chk-trade-proposals',{action:'server_create_proposal',accountFingerprint:fp(),symbol,side:args.side,orderType:args.order_type,quoteAmountUsdc:args.quote_amount_usdc,baseQuantity:args.base_quantity??null,limitPrice:args.limit_price??null,rationale:args.rationale,confidence:args.confidence??null,expiresInMinutes:args.expires_in_minutes??120,source:'chatgpt-workspace-v11'});}
 if(name==='list_trade_proposals')return await edge('chk-trade-proposals',{action:'server_list_proposals',accountFingerprint:fp(),limit:args.limit??40});
 if(name==='create_cancel_proposal'){const symbol=cleanSymbol(args.symbol);return await edge('chk-cancel-proposals',{action:'server_create_cancel',accountFingerprint:fp(),symbol,targetOrderId:args.target_order_id,targetOrderLinkId:args.target_order_link_id??'',rationale:args.rationale,confidence:args.confidence??null,expiresInMinutes:args.expires_in_minutes??120,replacementSide:args.replacement_side??null,replacementOrderType:args.replacement_order_type??null,replacementQuoteAmountUsdc:args.replacement_quote_amount_usdc??null,replacementBaseQuantity:args.replacement_base_quantity??null,replacementLimitPrice:args.replacement_limit_price??null,replacementRationale:args.replacement_rationale??null,replacementConfidence:args.replacement_confidence??null});}
 if(name==='list_cancel_proposals')return await edge('chk-cancel-proposals',{action:'server_list_cancel',accountFingerprint:fp(),limit:args.limit??40});
 if(name==='create_note')return await edge('chk-crypto-notes',{action:'server_create_note',accountFingerprint:fp(),content:args.content,exchange:args.exchange??'GLOBAL',kind:args.kind??'ANALYSIS'});
 if(name==='list_notes')return await edge('chk-crypto-notes',{action:'server_list_notes',accountFingerprint:fp(),limit:args.limit??100});
 throw new Error(`Tool non canonique: ${name}`);
}

async function handleMcp(req,res){let parsed;try{parsed=JSON.parse(await bodyText(req));}catch{return json(res,400,{jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}});}const run=async msg=>{if(msg?.method==='initialize')return{jsonrpc:'2.0',id:msg.id,result:{protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'chk-crypto-workspace',version:SERVER_VERSION},instructions:'CHK Crypto canonique. Dépôt officiel Chasmet/Binance-bybyt-. Binance lecture; Bybit EU Spot lecture/analyse. Les outils create_* créent uniquement des propositions/notes. Aucun ordre réel n’est exécuté par MCP; auto-confirmation APK possible si autorisée ; vérifier Bybit avant rapport.'}};if(msg?.method==='tools/list')return{jsonrpc:'2.0',id:msg.id,result:{tools}};if(msg?.method==='tools/call'){const name=String(msg?.params?.name||'');try{const data=await executeTool(name,msg?.params?.arguments||{});return rpcResult(msg.id,data,`${name} • CHK Crypto canonique v11.`);}catch(e){return{jsonrpc:'2.0',id:msg.id,result:{isError:true,content:[{type:'text',text:`${name}: ${String(e.message||e).slice(0,400)}`}]}};}}return{jsonrpc:'2.0',id:msg?.id??null,error:{code:-32601,message:'Method not found'}};};const out=Array.isArray(parsed)?await Promise.all(parsed.map(run)):await run(parsed);return json(res,200,out,{'mcp-protocol-version':'2025-06-18'});}

const server=http.createServer(async(req,res)=>{try{const url=new URL(req.url,`https://${req.headers.host}`);if(validMcpPath(url.pathname))return handleMcp(req,res);if(url.pathname==='/health')return json(res,200,{ok:true,name:'chk-crypto-workspace',version:SERVER_VERSION,canonical:true,repository:CANONICAL_REPO,legacyToolSurface:false});const raw=req.method==='GET'||req.method==='HEAD'?undefined:await bodyText(req);const target=new URL(req.url,`http://127.0.0.1:${UPSTREAM_PORT}`);const r=await fetch(target,{method:req.method,headers:{...(req.headers['content-type']?{'content-type':req.headers['content-type']}:{}),accept:req.headers.accept||'application/json'},body:raw});const text=await r.text();res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/json','cache-control':'no-store'});res.end(text);}catch(e){console.error('v11_request_error',e?.message||e);json(res,500,{error:'server_error',message:String(e.message||e).slice(0,300)});}});

try{await waitForUpstream();server.listen(PORT,'0.0.0.0',()=>console.log(`CHK Crypto MCP v${SERVER_VERSION} canonical tools only on :${PORT}`));}catch(e){console.error(e);child.kill('SIGTERM');process.exit(1);}

