import http from 'node:http';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { URL } from 'node:url';

const PORT=Number(process.env.PORT||3000);
const UPSTREAM_PORT=Number(process.env.V16_UPSTREAM_PORT||(PORT+10));
const SIGNING_UPSTREAM_PORT=UPSTREAM_PORT+30;
const SERVER_VERSION='16.0.1';
const BYBIT_API_KEY=String(process.env.BYBIT_API_KEY||'').trim();
const CHK_INTERNAL_TOKEN=String(process.env.CHK_INTERNAL_TOKEN||'');
const MCP_LINK_TOKEN=String(process.env.MCP_LINK_TOKEN||'');
const EDGE_URL=String(process.env.SUPABASE_EDGE_URL||'');
const here=path.dirname(fileURLToPath(import.meta.url));
if(!BYBIT_API_KEY)throw new Error('BYBIT_API_KEY missing');
if(!CHK_INTERNAL_TOKEN)throw new Error('CHK_INTERNAL_TOKEN missing');
if(!MCP_LINK_TOKEN)throw new Error('MCP_LINK_TOKEN missing');
if(!EDGE_URL)throw new Error('SUPABASE_EDGE_URL missing');

const child=spawn(process.execPath,['server-v15.mjs'],{cwd:here,env:{...process.env,PORT:String(UPSTREAM_PORT),V15_UPSTREAM_PORT:String(UPSTREAM_PORT+10)},stdio:['ignore','inherit','inherit']});
child.on('exit',(code,signal)=>console.error(`v15 exited code=${code} signal=${signal}`));

const ACCOUNT_FINGERPRINT=crypto.createHash('sha256').update(BYBIT_API_KEY).digest('hex');
function constantEqual(a,b){const A=Buffer.from(String(a||''));const B=Buffer.from(String(b||''));return A.length===B.length&&crypto.timingSafeEqual(A,B);}
function validLegacyMcpPath(p){return p.startsWith('/mcp/')&&constantEqual(p.slice(5),MCP_LINK_TOKEN);}
function isMcpPath(p){return p==='/mcp'||validLegacyMcpPath(p);}
function json(res,status,data,extra={}){const body=JSON.stringify(data);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff','content-length':Buffer.byteLength(body),...extra});res.end(body);}
async function bodyText(req,max=2_000_000){let body='';for await(const chunk of req){body+=chunk;if(body.length>max)throw new Error('request_too_large');}return body;}
function chartUrl(){const u=new URL(EDGE_URL);u.pathname=u.pathname.replace(/\/chk-binance-workspace-latest\/?$/,`/chk-chart-control`);return u.toString();}
async function chartBridge(payload){const r=await fetch(chartUrl(),{method:'POST',headers:{'content-type':'application/json','x-chk-internal-token':CHK_INTERNAL_TOKEN,accept:'application/json','user-agent':'chk-crypto-workspace-v16'},body:JSON.stringify({...payload,accountFingerprint:ACCOUNT_FINGERPRINT})});const text=await r.text();let data;try{data=JSON.parse(text||'{}');}catch{data={raw:text};}if(!r.ok)throw new Error(`chk-chart-control ${r.status}: ${data?.error||data?.message||text.slice(0,180)}`);return data;}
async function upstreamRpc(msg){const r=await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/mcp`,{method:'POST',headers:{'content-type':'application/json','mcp-protocol-version':'2025-06-18',accept:'application/json'},body:JSON.stringify(msg)});const text=await r.text();if(!r.ok)throw new Error(`v15 ${r.status}: ${text.slice(0,180)}`);return JSON.parse(text||'{}');}
function result(id,data,text){return{jsonrpc:'2.0',id,result:{content:[{type:'text',text}],structuredContent:data}};}
function imageResult(id,data,text,b64){const content=[{type:'text',text}];if(b64)content.push({type:'image',data:b64,mimeType:'image/png'});return{jsonrpc:'2.0',id,result:{content,structuredContent:data}};}
function cleanSymbol(v){const s=String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,30);const out=s.endsWith('USDC')?s:s.endsWith('USDT')?`${s.slice(0,-4)}USDC`:`${s}USDC`;if(!/^[A-Z0-9]{2,24}USDC$/.test(out)||out==='USDCUSDC')throw new Error('Paire CRYPTO/USDC invalide');return out;}
const TIMEFRAMES=new Set(['1m','3m','5m','15m','30m','1h','2h','4h','6h','12h','1d','3d','1w']);
function timeframe(v){const t=String(v||'').trim().toLowerCase();if(!TIMEFRAMES.has(t))throw new Error('Timeframe invalide');return t;}
function finite(v,name){const n=Number(v);if(!Number.isFinite(n))throw new Error(`${name} invalide`);return n;}

const readAnn={readOnlyHint:true,destructiveHint:false,idempotentHint:true,openWorldHint:false};
const writeAnn={readOnlyHint:false,destructiveHint:false,idempotentHint:false,openWorldHint:false};
const destructiveAnn={readOnlyHint:false,destructiveHint:true,idempotentHint:true,openWorldHint:false};
const noProps={type:'object',properties:{},additionalProperties:false};
const chartTools=[
 {name:'get_chart_state',title:'Lire le graphique CHK Crypto',description:'Retourne l’état exact du graphique actuellement synchronisé dans l’APK : paire, timeframe, viewport, indicateurs, dessins et données visibles.',inputSchema:noProps,annotations:readAnn},
 {name:'get_chart_visible_range',title:'Lire la plage visible du graphique',description:'Retourne la plage de temps réellement visible, le nombre de bougies, le décalage historique et Auto Scale.',inputSchema:noProps,annotations:readAnn},
 {name:'get_chart_candles',title:'Lire les bougies du graphique',description:'Retourne les OHLCV actuellement chargées par le même graphique que l’utilisateur. visible_only limite la réponse au viewport visible.',inputSchema:{type:'object',properties:{visible_only:{type:'boolean'},limit:{type:'integer',minimum:10,maximum:1000}},additionalProperties:false},annotations:readAnn},
 {name:'get_chart_indicators',title:'Lire les indicateurs du graphique',description:'Retourne la configuration MA/EMA/RSI/MACD/ATR/Bollinger/volume et les dernières valeurs calculées.',inputSchema:noProps,annotations:readAnn},
 {name:'get_chart_drawings',title:'Lire les dessins techniques',description:'Retourne tous les supports, résistances, trendlines, zones BUY/SELL, invalidations, TP et re-buy placés sur le graphique.',inputSchema:noProps,annotations:readAnn},
 {name:'get_chart_crosshair',title:'Lire le crosshair du graphique',description:'Retourne la position réelle du crosshair synchronisé avec l’APK.',inputSchema:noProps,annotations:readAnn},
 {name:'get_chart_snapshot',title:'Voir le graphique CHK Crypto',description:'Retourne une image PNG réelle du graphique actuellement affiché dans l’APK, si un snapshot récent est disponible.',inputSchema:noProps,annotations:readAnn},
 {name:'set_chart_symbol',title:'Changer la paire du graphique',description:'Change directement la paire CRYPTO/USDC affichée dans CHK Crypto. Aucune confirmation trading nécessaire.',inputSchema:{type:'object',properties:{symbol:{type:'string'}},required:['symbol'],additionalProperties:false},annotations:writeAnn},
 {name:'set_chart_timeframe',title:'Changer le timeframe du graphique',description:'Change directement le timeframe réel du graphique.',inputSchema:{type:'object',properties:{timeframe:{type:'string',enum:[...TIMEFRAMES]}},required:['timeframe'],additionalProperties:false},annotations:writeAnn},
 {name:'set_chart_indicators',title:'Configurer les indicateurs du graphique',description:'Configure MA, EMA, volume, Bollinger, RSI, MACD et ATR sur le graphique réel.',inputSchema:{type:'object',properties:{ma:{type:'array',items:{type:'integer',minimum:1,maximum:500},maxItems:12},ema:{type:'array',items:{type:'integer',minimum:1,maximum:500},maxItems:12},volume:{type:'boolean'},bollinger:{type:'boolean'},rsi:{type:'integer',minimum:2,maximum:100},macd:{type:'boolean'},atr:{type:'integer',minimum:2,maximum:100}},additionalProperties:false},annotations:writeAnn},
 {name:'set_chart_visible_range',title:'Régler la plage visible',description:'Règle le viewport par timestamps ou directement par nombre de bougies/décalage.',inputSchema:{type:'object',properties:{start_timestamp:{type:'integer'},end_timestamp:{type:'integer'},visible_count:{type:'integer',minimum:12,maximum:600},offset_from_end:{type:'integer',minimum:0}},additionalProperties:false},annotations:writeAnn},
 {name:'chart_zoom_in',title:'Zoomer le graphique',description:'Zoome le viewport réel du graphique.',inputSchema:noProps,annotations:writeAnn},
 {name:'chart_zoom_out',title:'Dézoomer le graphique',description:'Dézoome le viewport réel du graphique.',inputSchema:noProps,annotations:writeAnn},
 {name:'chart_pan_left',title:'Déplacer le graphique vers l’historique',description:'Déplace le viewport vers les bougies plus anciennes.',inputSchema:{type:'object',properties:{candles:{type:'integer',minimum:1,maximum:500}},additionalProperties:false},annotations:writeAnn},
 {name:'chart_pan_right',title:'Déplacer le graphique vers le présent',description:'Déplace le viewport vers les bougies plus récentes.',inputSchema:{type:'object',properties:{candles:{type:'integer',minimum:1,maximum:500}},additionalProperties:false},annotations:writeAnn},
 {name:'chart_go_to_latest',title:'Revenir au dernier prix',description:'Ramène directement le graphique sur la dernière bougie.',inputSchema:noProps,annotations:writeAnn},
 {name:'chart_reset_view',title:'Réinitialiser la vue du graphique',description:'Réinitialise zoom, pan, Auto Scale et crosshair.',inputSchema:noProps,annotations:writeAnn},
 {name:'set_chart_crosshair',title:'Positionner le crosshair',description:'Positionne et centre le crosshair sur une bougie/valeur précise.',inputSchema:{type:'object',properties:{timestamp:{type:'integer'},price:{type:'number',exclusiveMinimum:0}},additionalProperties:false},annotations:writeAnn},
 {name:'add_chart_drawing',title:'Ajouter un dessin technique',description:'Ajoute un support, résistance, trendline, ligne, zone BUY/SELL, invalidation, TP ou re-buy avec ID persistant.',inputSchema:{type:'object',properties:{id:{type:'string'},type:{type:'string',enum:['support','resistance','trendline','horizontal','rectangle','zone','buy','sell','buy_zone','sell_zone','invalidation','tp','rebuy']},label:{type:'string'},price1:{type:'number',exclusiveMinimum:0},price2:{type:'number',exclusiveMinimum:0},time1:{type:'integer'},time2:{type:'integer'}},required:['type','price1'],additionalProperties:false},annotations:writeAnn},
 {name:'update_chart_drawing',title:'Modifier un dessin technique',description:'Déplace ou modifie un dessin existant en conservant son ID.',inputSchema:{type:'object',properties:{id:{type:'string'},type:{type:'string'},label:{type:'string'},price1:{type:'number',exclusiveMinimum:0},price2:{type:'number',exclusiveMinimum:0},time1:{type:'integer'},time2:{type:'integer'}},required:['id'],additionalProperties:false},annotations:writeAnn},
 {name:'remove_chart_drawing',title:'Supprimer un dessin technique',description:'Supprime un dessin précis du graphique par ID.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id'],additionalProperties:false},annotations:destructiveAnn},
 {name:'clear_chart_drawings',title:'Effacer les dessins du graphique',description:'Efface tous les dessins techniques du graphique.',inputSchema:noProps,annotations:destructiveAnn},
 {name:'set_chart_auto_scale',title:'Régler Auto Scale',description:'Active ou désactive Auto Scale sur l’axe des prix.',inputSchema:{type:'object',properties:{enabled:{type:'boolean'}},required:['enabled'],additionalProperties:false},annotations:writeAnn},
 {name:'set_chart_profile',title:'Sélectionner un profil graphique',description:'Applique directement le profil SCALP, INTRADAY ou SWING.',inputSchema:{type:'object',properties:{profile:{type:'string',enum:['SCALP','INTRADAY','SWING']}},required:['profile'],additionalProperties:false},annotations:writeAnn},
 {name:'get_multi_timeframe_analysis_data',title:'Données techniques multi-timeframe',description:'Retourne en une opération les OHLCV et indicateurs 1m/5m/15m/1h/4h/1D/1W depuis Bybit EU.',inputSchema:{type:'object',properties:{symbol:{type:'string'},limit:{type:'integer',minimum:60,maximum:400}},required:['symbol'],additionalProperties:false},annotations:readAnn},
];
const names=new Set(chartTools.map(t=>t.name));

async function currentChart(){return chartBridge({action:'get_state'});}
async function enqueue(op,args={}){return chartBridge({action:'enqueue_command',command:{op,args}});}
function statePart(root){return root?.state&&typeof root.state==='object'?root.state:{};}
function marketPart(root){return root?.market&&typeof root.market==='object'?root.market:{};}

async function handleChartCall(msg,name,a){
 if(name==='get_chart_state'){const d=await currentChart();return result(msg.id,d,'État réel du graphique CHK Crypto récupéré.');}
 if(name==='get_chart_visible_range'){const d=await currentChart();const s=statePart(d),m=marketPart(d);const out={symbol:s.symbol||m.symbol,timeframe:s.timeframe||m.timeframe,viewport:s.viewport||{},visibleStart:m.visibleStart||0,visibleEnd:m.visibleEnd||0,updated_at:d.updated_at};return result(msg.id,out,'Plage visible réelle du graphique récupérée.');}
 if(name==='get_chart_candles'){const d=await currentChart();const s=statePart(d),m=marketPart(d);let candles=Array.isArray(m.candles)?m.candles:[];if(a.visible_only){const v=s.viewport||{};const count=Math.max(1,Number(v.visibleCount||100));const offset=Math.max(0,Number(v.offsetFromEnd||0));const end=Math.max(0,candles.length-offset);candles=candles.slice(Math.max(0,end-count),end);}const lim=Math.max(10,Math.min(1000,Number(a.limit||candles.length||1000)));candles=candles.slice(-lim);const out={symbol:s.symbol||m.symbol,timeframe:s.timeframe||m.timeframe,format:['time','open','high','low','close','volume'],candles};return result(msg.id,out,`${candles.length} bougie(s) du graphique CHK Crypto.`);}
 if(name==='get_chart_indicators'){const d=await currentChart();const s=statePart(d),m=marketPart(d);const out={symbol:s.symbol||m.symbol,timeframe:s.timeframe||m.timeframe,configuration:s.indicators||{},values:m.indicators||{}};return result(msg.id,out,'Indicateurs du graphique récupérés.');}
 if(name==='get_chart_drawings'){const d=await currentChart();const s=statePart(d);const drawings=Array.isArray(s.drawings)?s.drawings:[];return result(msg.id,{symbol:s.symbol,timeframe:s.timeframe,drawings},`${drawings.length} dessin(s) technique(s).`);}
 if(name==='get_chart_crosshair'){const d=await currentChart();const s=statePart(d);return result(msg.id,{symbol:s.symbol,timeframe:s.timeframe,crosshair:s?.viewport?.crosshair||{}},'Crosshair réel du graphique récupéré.');}
 if(name==='get_chart_snapshot'){const d=await chartBridge({action:'get_snapshot'});if(!d.url)return imageResult(msg.id,d,'Aucun snapshot PNG du graphique n’est encore disponible.',null);const r=await fetch(d.url);if(!r.ok)throw new Error(`snapshot HTTP ${r.status}`);const buf=Buffer.from(await r.arrayBuffer());return imageResult(msg.id,{ok:true,snapshot_updated_at:d.snapshot_updated_at,size:buf.length},'Snapshot PNG réel du graphique CHK Crypto.',buf.toString('base64'));}
 if(name==='set_chart_symbol'){const symbol=cleanSymbol(a.symbol);const d=await enqueue('set_symbol',{symbol});return result(msg.id,d,`CHK Crypto va ouvrir ${symbol}.`);}
 if(name==='set_chart_timeframe'){const tf=timeframe(a.timeframe);const d=await enqueue('set_timeframe',{timeframe:tf});return result(msg.id,d,`Timeframe ${tf} envoyé au graphique réel.`);}
 if(name==='set_chart_indicators'){const d=await currentChart();const current={...(statePart(d).indicators||{})};for(const k of ['ma','ema','volume','bollinger','rsi','macd','atr'])if(a[k]!==undefined)current[k]=a[k];const q=await enqueue('set_indicators',current);return result(msg.id,q,'Configuration des indicateurs envoyée au graphique réel.');}
 if(name==='set_chart_visible_range'){let args={};if(a.visible_count!==undefined)args.visible_count=Math.max(12,Math.min(600,Number(a.visible_count)));if(a.offset_from_end!==undefined)args.offset_from_end=Math.max(0,Number(a.offset_from_end));if(a.start_timestamp!==undefined||a.end_timestamp!==undefined){const d=await currentChart();const candles=Array.isArray(marketPart(d).candles)?marketPart(d).candles:[];if(candles.length){const start=Number(a.start_timestamp||candles[0][0]);const end=Number(a.end_timestamp||candles[candles.length-1][0]);let si=candles.findIndex(c=>Number(c?.[0])>=start);if(si<0)si=0;let ei=candles.length-1;for(let i=candles.length-1;i>=0;i--){if(Number(candles[i]?.[0])<=end){ei=i;break;}}if(ei<si)[si,ei]=[ei,si];args.visible_count=Math.max(12,Math.min(600,ei-si+1));args.offset_from_end=Math.max(0,candles.length-1-ei);}}const q=await enqueue('set_visible_range',args);return result(msg.id,q,'Plage visible envoyée au viewport réel.');}
 if(name==='chart_zoom_in')return result(msg.id,await enqueue('zoom_in'), 'Zoom avant envoyé au graphique.');
 if(name==='chart_zoom_out')return result(msg.id,await enqueue('zoom_out'), 'Zoom arrière envoyé au graphique.');
 if(name==='chart_pan_left')return result(msg.id,await enqueue('pan_left',{candles:Math.max(1,Math.min(500,Number(a.candles||20)))}),'Déplacement vers l’historique envoyé.');
 if(name==='chart_pan_right')return result(msg.id,await enqueue('pan_right',{candles:Math.max(1,Math.min(500,Number(a.candles||20)))}),'Déplacement vers le présent envoyé.');
 if(name==='chart_go_to_latest')return result(msg.id,await enqueue('go_to_latest'),'Retour au dernier prix envoyé.');
 if(name==='chart_reset_view')return result(msg.id,await enqueue('reset_view'),'Reset du viewport envoyé.');
 if(name==='set_chart_crosshair'){const args={};if(a.timestamp!==undefined)args.timestamp=Number(a.timestamp);if(a.price!==undefined)args.price=finite(a.price,'price');return result(msg.id,await enqueue('set_crosshair',args),'Crosshair envoyé au graphique réel.');}
 if(name==='add_chart_drawing'){const drawing={id:String(a.id||crypto.randomUUID()),type:String(a.type),label:String(a.label||'').slice(0,120),price1:finite(a.price1,'price1')};for(const k of ['price2','time1','time2'])if(a[k]!==undefined)drawing[k]=Number(a[k]);return result(msg.id,await enqueue('add_drawing',{drawing}),'Dessin technique ajouté à la file du graphique.');}
 if(name==='update_chart_drawing'){const d=await currentChart();const arr=Array.isArray(statePart(d).drawings)?statePart(d).drawings:[];const existing=arr.find(x=>x?.id===a.id);if(!existing)throw new Error('Dessin introuvable');const drawing={...existing,...a,id:a.id};return result(msg.id,await enqueue('update_drawing',{drawing}),'Modification du dessin envoyée.');}
 if(name==='remove_chart_drawing')return result(msg.id,await enqueue('remove_drawing',{id:String(a.id)}),'Suppression du dessin envoyée.');
 if(name==='clear_chart_drawings')return result(msg.id,await enqueue('clear_drawings'),'Effacement des dessins envoyé.');
 if(name==='set_chart_auto_scale')return result(msg.id,await enqueue('set_auto_scale',{enabled:a.enabled===true}),'Réglage Auto Scale envoyé.');
 if(name==='set_chart_profile')return result(msg.id,await enqueue('set_profile',{profile:String(a.profile).toUpperCase()}),'Profil graphique envoyé.');
 if(name==='get_multi_timeframe_analysis_data'){const symbol=cleanSymbol(a.symbol);const limit=Math.max(60,Math.min(400,Number(a.limit||220)));const frames=['1m','5m','15m','1h','4h','1d','1w'];const values=await Promise.all(frames.map(tf=>analyseTimeframe(symbol,tf,limit)));const out={exchange:'BYBIT_EU',symbol,timeframes:Object.fromEntries(values.map(v=>[v.timeframe,v]))};return result(msg.id,out,`Analyse multi-timeframe ${symbol}: ${frames.join(' / ')}.`);}
 throw new Error(`chart tool not handled: ${name}`);
}

const TF_MAP={"1m":"1","5m":"5","15m":"15","1h":"60","4h":"240","1d":"D","1w":"W"};
async function fetchBybitKlines(symbol,tf,limit){let last;for(const base of ['https://api.bybit.eu','https://api.bybit.com']){try{const u=`${base}/v5/market/kline?category=spot&symbol=${encodeURIComponent(symbol)}&interval=${TF_MAP[tf]}&limit=${limit}`;const r=await fetch(u,{headers:{accept:'application/json','user-agent':'CHK-Crypto-MCP-v16'}});const j=await r.json();if(!r.ok||Number(j.retCode)!==0)throw new Error(j.retMsg||`HTTP ${r.status}`);return (j?.result?.list||[]).map(x=>({time:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5])})).filter(x=>Object.values(x).every(Number.isFinite)).sort((a,b)=>a.time-b.time);}catch(e){last=e;}}throw last||new Error('Bybit kline unavailable');}
function ema(values,p){if(!values.length)return[];const k=2/(p+1);let e=values[0];return values.map((v,i)=>(e=i===0?v:v*k+e*(1-k)));}
function smaLast(v,p){const w=v.slice(-p);return w.reduce((a,b)=>a+b,0)/Math.max(1,w.length);}
function rsi(v,p=14){if(v.length<=p)return 50;let g=0,l=0;for(let i=1;i<=p;i++){const d=v[i]-v[i-1];if(d>=0)g+=d;else l-=d;}let ag=g/p,al=l/p;for(let i=p+1;i<v.length;i++){const d=v[i]-v[i-1];ag=(ag*(p-1)+Math.max(d,0))/p;al=(al*(p-1)+Math.max(-d,0))/p;}return al===0?100:100-100/(1+ag/al);}
function atr(c,p=14){const tr=[];for(let i=1;i<c.length;i++)tr.push(Math.max(c[i].high-c[i].low,Math.abs(c[i].high-c[i-1].close),Math.abs(c[i].low-c[i-1].close)));const w=tr.slice(-p);return w.reduce((a,b)=>a+b,0)/Math.max(1,w.length);}
function boll(v,p=20){const w=v.slice(-p),mid=w.reduce((a,b)=>a+b,0)/Math.max(1,w.length),sd=Math.sqrt(w.reduce((a,b)=>a+(b-mid)**2,0)/Math.max(1,w.length));return{upper:mid+2*sd,middle:mid,lower:mid-2*sd};}
function std(v){if(v.length<2)return 0;const m=v.reduce((a,b)=>a+b,0)/v.length;return Math.sqrt(v.reduce((a,b)=>a+(b-m)**2,0)/v.length);}
async function analyseTimeframe(symbol,tf,limit){const c=await fetchBybitKlines(symbol,tf,limit);const closes=c.map(x=>x.close);const fast=ema(closes,12),slow=ema(closes,26),line=closes.map((_,i)=>fast[i]-slow[i]),sig=ema(line,9);const bb=boll(closes);const returns=[];for(let i=1;i<closes.length;i++)if(closes[i-1]>0)returns.push((closes[i]/closes[i-1]-1)*100);const recent=c.slice(-60),vols=c.slice(-20).map(x=>x.volume);return{timeframe:tf,lastPrice:closes.at(-1),ohlcv:c.map(x=>[x.time,x.open,x.high,x.low,x.close,x.volume]),ma:{7:smaLast(closes,7),14:smaLast(closes,14),28:smaLast(closes,28)},ema:{9:ema(closes,9).at(-1),20:ema(closes,20).at(-1),50:ema(closes,50).at(-1),200:ema(closes,200).at(-1)},rsi14:rsi(closes,14),macd:{line:line.at(-1),signal:sig.at(-1),histogram:line.at(-1)-sig.at(-1)},atr14:atr(c,14),bollinger:bb,recentHigh:Math.max(...recent.map(x=>x.high)),recentLow:Math.min(...recent.map(x=>x.low)),averageVolume:vols.reduce((a,b)=>a+b,0)/Math.max(1,vols.length),volatilityPct:std(returns.slice(-60))};}

async function handleOne(msg,requestPath='/mcp'){
 if(msg?.method==='initialize'){const out=await upstreamRpc(msg);if(out?.result){out.result.serverInfo={name:'chk-crypto-workspace',version:SERVER_VERSION};out.result.capabilities=out.result.capabilities||{};out.result.capabilities.tools={...(out.result.capabilities.tools||{}),listChanged:true};out.result.instructions='CHK Crypto v16. Le MCP lit et pilote le même graphique que l APK: paire, timeframe, viewport, crosshair, indicateurs, dessins et snapshot PNG. Contrôle graphique direct autorisé. Les ordres Bybit réels restent obligatoirement soumis à confirmation dans l APK.';}console.log(`[MCP v16] initialize path=${requestPath}`);return out;}
 if(msg?.method==='tools/list'){const out=await upstreamRpc(msg);const tools=Array.isArray(out?.result?.tools)?out.result.tools:[];for(const t of chartTools)if(!tools.some(x=>x?.name===t.name))tools.push(t);if(out?.result)out.result.tools=tools;console.log(`[MCP v16] tools/list count=${tools.length} chart=${chartTools.length}`);return out;}
 if(msg?.method!=='tools/call')return upstreamRpc(msg);
 const name=String(msg?.params?.name||'');if(!names.has(name))return upstreamRpc(msg);
 return handleChartCall(msg,name,msg?.params?.arguments||{});
}
async function proxy(req,res,raw){const target=new URL(req.url,`http://127.0.0.1:${UPSTREAM_PORT}`);const r=await fetch(target,{method:req.method,headers:{...(req.headers['content-type']?{'content-type':req.headers['content-type']}:{}),...(req.headers.accept?{accept:req.headers.accept}:{}),...(req.headers['mcp-protocol-version']?{'mcp-protocol-version':req.headers['mcp-protocol-version']}:{})},body:raw});const text=await r.text();res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store'});res.end(text);}
async function proxySigning(req,res,raw){const r=await fetch(`http://127.0.0.1:${SIGNING_UPSTREAM_PORT}/ci/android-signing`,{method:req.method,headers:{...(req.headers.authorization?{authorization:req.headers.authorization}:{}),...(req.headers.accept?{accept:req.headers.accept}:{})},body:raw});const text=await r.text();res.writeHead(r.status,{'content-type':r.headers.get('content-type')||'application/json; charset=utf-8','cache-control':'no-store'});res.end(text);}
async function waitForUpstream(){for(let i=0;i<120;i++){try{const r=await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/health`);if(r.ok)return;}catch{}await new Promise(r=>setTimeout(r,250));}throw new Error('v15_startup_timeout');}
const server=http.createServer(async(req,res)=>{try{const raw=req.method==='GET'||req.method==='HEAD'?undefined:await bodyText(req);const u=new URL(req.url,`https://${req.headers.host}`);if(u.pathname==='/ci/android-signing')return proxySigning(req,res,raw);if(u.pathname.startsWith('/mcp/')&&!validLegacyMcpPath(u.pathname))return json(res,403,{error:'mcp_forbidden'});if(isMcpPath(u.pathname)&&req.method==='POST'){let parsed;try{parsed=JSON.parse(raw||'{}');}catch{return json(res,400,{jsonrpc:'2.0',id:null,error:{code:-32700,message:'Parse error'}});}const out=Array.isArray(parsed)?await Promise.all(parsed.map(x=>handleOne(x,u.pathname))):await handleOne(parsed,u.pathname);return json(res,200,out,{'mcp-protocol-version':'2025-06-18'});}if(u.pathname==='/debug/tool-names')return json(res,200,{version:SERVER_VERSION,chartTools:chartTools.map(t=>t.name),chartToolCount:chartTools.length});if(u.pathname==='/health'){let upstream={};try{const r=await fetch(`http://127.0.0.1:${UPSTREAM_PORT}/health`);upstream=await r.json();}catch{}return json(res,200,{...upstream,gatewayVersion:SERVER_VERSION,chartControl:true,chartSnapshotPng:true,multiTimeframe:true,legacyTokenizedMcpCompat:true,toolListChanged:true,signingOidcPassthrough:true});}return proxy(req,res,raw);}catch(e){console.error('v16_request_error',e?.stack||e?.message||e);return json(res,500,{error:'server_error',message:String(e?.message||e).slice(0,260)});}});
try{await waitForUpstream();server.listen(PORT,'0.0.0.0',()=>console.log(`CHK Crypto Gateway v${SERVER_VERSION} shared chart control on :${PORT}`));}catch(e){console.error(e);child.kill('SIGTERM');process.exit(1);}
